import Head from 'next/head'
import Header from '../component/Header'
import Nav from '../component/Nav'
import request from '../utilis/request'
import Result from '../component/Result'

export default function Home({results}) {
  console.log(results)
  return (
    <div className=''>
    <Head>
      <title>Hulu</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  <Header />
  <Nav />
  <Result results={results}/>
  </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre

  const requests = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`).then(res => res.json())

  return {
    props : {
      results: requests.results
    }
  }
}
